/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ensamblador;
import java.io.*;
import javax.swing.*;
/**
 *
 * @author masue
 */
public class JFassembly extends javax.swing.JFrame {
    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    GestionArchivo admon = new GestionArchivo();
    String contenido;
    
    /**
     * Creates new form JFassembly
     */
    public JFassembly() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrirAsm = new javax.swing.JButton();
        btnGuardarLst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ensamblador Z80");

        btnAbrirAsm.setText("Abrir archivo fuente");
        btnAbrirAsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirAsmActionPerformed(evt);
            }
        });

        btnGuardarLst.setText("Guardar Archivo LST");
        btnGuardarLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbrirAsm)
                    .addComponent(btnGuardarLst))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAbrirAsm)
                .addGap(65, 65, 65)
                .addComponent(btnGuardarLst)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirAsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirAsmActionPerformed
        if(this.seleccionado.showDialog(null, "Abrir archivo") == JFileChooser.APPROVE_OPTION){
            this.archivo = this.seleccionado.getSelectedFile();
            if(this.archivo.canRead() && this.archivo.getName().endsWith("asm") ){
                this.contenido = admon.abrirArchivo(archivo);
                JOptionPane.showMessageDialog(null, "Se abrió el archivo con éxito");
            }
            else{
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un archivo con extensión .asm");
            }
        }
    }//GEN-LAST:event_btnAbrirAsmActionPerformed

    private void btnGuardarLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLstActionPerformed
        if(this.seleccionado.showDialog(null, "Guardar Archivo") == JFileChooser.APPROVE_OPTION){
            this.archivo = this.seleccionado.getSelectedFile();
            if(archivo.getName().endsWith("lst")){
                if(admon.guardarArchivo(archivo, this.contenido)){
                    JOptionPane.showMessageDialog(null, "Se guardo el archivo con éxito");
                }else{
                    JOptionPane.showMessageDialog(null, "Error al guardar archivo");
                }
            }else{
                JOptionPane.showMessageDialog(null, "El archivo debe guardarse con extensión .lst");
            }
        }
    }//GEN-LAST:event_btnGuardarLstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFassembly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFassembly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFassembly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFassembly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFassembly().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirAsm;
    private javax.swing.JButton btnGuardarLst;
    // End of variables declaration//GEN-END:variables
}
